const ADD_INITIAL_VALUE = "ADD_INITIAL_VALUE";
const SET_STORY_DETAILS = "SET_STORY_DETAILS";
const ACTIVE_STORY_DETAILS = "ACTIVE_STORY_DETAILS";
const SET_ROOM_CONFIG = "SET_ROOM_CONFIG";
const OPEN_CLOSE_POP_UPS = "OPEN_CLOSE_POP_UPS";
const SET_STORIES = "SET_STORIES";

export {
    ADD_INITIAL_VALUE,
    SET_STORY_DETAILS,
    ACTIVE_STORY_DETAILS,
    SET_ROOM_CONFIG,
    OPEN_CLOSE_POP_UPS,
    SET_STORIES,
};
